services:
  - type: web
    name: amaans-music-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_R2_PUBLIC_URL
        sync: false
      - key: NEXT_PUBLIC_WORKER_URL
        sync: false
